name: Video Process

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
      - name: Checkout source
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Install dependent
        run: |
          aria2c https://johnvansickle.com/ffmpeg/builds/ffmpeg-git-amd64-static.tar.xz
          ffmpeg_path=$(tar tf ffmpeg-git-amd64-static.tar.xz | grep amd64-static/ffmpeg)
          tar xf ffmpeg-git-amd64-static.tar.xz $ffmpeg_path && rm ffmpeg-git-amd64-static.tar.xz
          chmod +x $ffmpeg_path
          sudo mv $ffmpeg_path /usr/local/bin/
          sudo pip3 install bs4
      
      - name: Setup task
        run: |
            python3 setup.py

      - name: Download video
        run: |
            aria2c --conf-path=./aria2.conf $(cat url.txt)
      
      - name: Process video
        run: |
          #ffmpeg -hide_banner -loglevel error -ss 3 -i $(cat video.txt) -vf "select=gt(scene\,0.4)" -frames:v 16 -vsync vfr -vf fps=fps=1/450 thumb%02d.jpg
          ffmpeg -hide_banner -loglevel error -i $(cat video.txt) -c copy -f hls -bsf:v h264_mp4toannexb -hls_list_size 0 -hls_segment_filename hls%4d.ts index.m3u8
          rm -rf $(cat video.txt)

      - name: Setup Git
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 700 ~/.ssh
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global user.email "github@chan.im"
          git config --global user.name "ghcdn"
      
      - name: Create Github repo
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: |
          curl \
          -X POST \
          -H "Authorization: token $ACCESS_TOKEN" \
          -H "Content-Type: application/json" \
          https://api.github.com/user/repos \
          -d "{\"name\": \"$(cat repo.txt)\"}"
      
      - name: Push to Github
        run: |
          mkdir -p gitdir/res/
          mkdir -p gitdir/img/
          mv *.m3u8 *.ts gitdir/res/
          # mv *.jpg gitdir/img/
          cd gitdir
          git init
          git add img res/*.m3u8
          git commit -m "add img and m3u8"
          git remote add origin git@github.com:ghcdn/$(cat ../repo.txt).git
          git push -u origin master
          for i in {0..9};do
            for j in {0..9};do
              files=(res/hls$i$j??.ts)
              if [ -f ${files[0]} ];then
                git add "${files[@]}"
                git commit -m "$i$j st commit"
                git push
              else
                exit 0
              fi
            done
          done
